[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
lib_deps = bodmer/TFT_eSPI@^2.5.43

build_flags =
  -D USER_SETUP_LOADED
  -D ILI9488_DRIVER
  -D TFT_WIDTH=480
  -D TFT_HEIGHT=320
  -D TFT_MISO=38
  -D TFT_MOSI=18
  -D TFT_SCLK=21
  -D TFT_CS=15
  -D TFT_DC=17
  -D TFT_RST=16
  -D TFT_BL=46
  -D TFT_BACKLIGHT_ON=HIGH
  -D USE_HSPI_PORT          ; ← THIS is the fix for ESP32-S3 core dump on init()
  -D LOAD_GLCD=1
  -D LOAD_FONT2
  -D LOAD_FONT4
  -D SMOOTH_FONT
  -D SPI_FREQUENCY=27000000