[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
lib_deps = 
  bodmer/TFT_eSPI@^2.5.43
  mathertel/RotaryEncoder

[env:esp32-s3-devkitc-1]
board = esp32-s3-devkitc-1
build_flags =
  -D BOARD_ESP32S3_DEVKITC
  -D USER_SETUP_LOADED
  -D ILI9488_DRIVER
  -D TFT_WIDTH=480
  -D TFT_HEIGHT=320
  -D TFT_BACKLIGHT_ON=HIGH
  -D USE_HSPI_PORT
  -D LOAD_GLCD=1
  -D LOAD_FONT2
  -D LOAD_FONT4
  -D SMOOTH_FONT
  -D SPI_FREQUENCY=27000000
  -I include                ; tells compiler to search include/ for headers

[env:esp32dev]
board = esp32dev
build_flags =
  -D BOARD_ESP32_DEVKIT
  -D USER_SETUP_LOADED
  -D ILI9488_DRIVER
  -D TFT_WIDTH=480
  -D TFT_HEIGHT=320
  -D TFT_BACKLIGHT_ON=HIGH
  -D LOAD_GLCD=1
  -D LOAD_FONT2
  -D LOAD_FONT4
  -D SMOOTH_FONT
  -D SPI_FREQUENCY=27000000
  -I include